### PR TITLE
fix: Test Bounty

### PR DESCRIPTION
**Pull request by Bhavyajain21**
/claim #1

### CODE REVIEW

**Comment by Bhavyajain21** [comment]
@cre4ture tested

**Comment by cre4ture** [comment]
you are kidding right?

**Comment by Bhavyajain21** [comment]
> you are kidding right?

I thought this was for testing

**Comment by cre4ture** [comment]
it was ^^
thanks for your attention. 
But I hope you do not expect to get 10$ for adding a whitespace?
;-)

**Comment by Bhavyajain21** [comment]
> it was ^^ thanks for your attention. But I hope you do not expect to get 10$ for adding a whitespace? ;-)

yes

**Pull request closed without merging**
